/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressBook } from "./AddressBook";

export { AddressBook__factory } from "./factories/AddressBook__factory";
